### PR TITLE
DASH-376 close zk connection on artificial expired event to prevent connection leak

### PR DESCRIPTION
**Pull request by clintropolis**

### CODE REVIEW

**Comment by aprilrd** [comment]
can we get some testz?

**Comment by clintropolis** [comment]
I'm not really sure how to test this, we don't have a reference to the previous clients after we reconnect in the expired event, i guess we could scan the log output or something, but that might be error prone. Thoughts?

**Comment by clintropolis** [comment]
Tests added, sort of hackish

**Comment by aprilrd** [comment]
:stars:

**Pull request merged**
